import { library } from '@fortawesome/fontawesome-svg-core';
import {
  // Navigation & UI
  faHome,
  faChevronRight,
  faChevronLeft,
  faXmark,
  faBars,
  faEllipsisVertical,
  
  // Assessment & Journey
  faHeart,
  faBrain,
  faShield,
  faWandSparkles,
  faStar,
  faPlay,
  faForward,
  faBackward,
  faQuestion,
  faLightbulb,
  faEye,
  faHandHoldingHeart,
  
  // Progress & Analytics
  faChartBar,
  faChartLine,
  faBullseye,
  faAward,
  faCheckCircle,
  faCircle,
  faClock,
  faCalendar,
  
  // Report & Data
  faFileText,
  faDownload,
  faShare,
  faBookOpen,
  faPrint,
  faDatabase,
  faChartPie,
  
  // Settings & Tools
  faKey,
  faCog,
  faUser,
  faUserCircle,
  faShieldAlt,
  faLock,
  
  // Emotions & Moods
  faSmile,
  faFrown,
  faMeh,
  faAngry,
  faSadTear,
  faGrin,
  faKiss,
  
  // Nature & Environments
  faTree,
  faWater,
  faMountain,
  faCloud,
  faSun,
  faMoon,
  faLeaf,
  faSnowflake,
  
  // Therapy & Health
  faHandsHelping,
  faMedkit,
  faPrescriptionBottle,
  faStethoscope,
  faUserMd,
  faComments,
  faUsers,
  faRocket,
  faFire,
  faShieldHeart,
  faRotateRight,
  faPuzzlePiece,
  faSeedling,
  faWind,
  faDumbbell,
  faAppleWhole,
  faSitemap,
  faTable,
  faClipboard,
  faHeartPulse,
  
  // Actions & Interactions
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  
  // Alerts & Status
  faExclamationTriangle,
  faInfoCircle,
  faExclamationCircle,
  faTimes,
  faCheck,
  
  // Design & Creative
  faPalette,
  faPaintBrush,
  faSwatchbook,
  faEyeDropper,
  faShapes,
  faCrop,
  faImage,
  
  
} from '@fortawesome/free-solid-svg-icons';

import {
  faHeart as faHeartRegular,
  faStar as faStarRegular,
  faCircle as faCircleRegular,
  faCheckCircle as faCheckCircleRegular,
  faUser as faUserRegular,
  faSmile as faSmileRegular,
  faFrown as faFrownRegular,
  faMeh as faMehRegular,
} from '@fortawesome/free-regular-svg-icons';

// Add icons to the library
library.add(
  // Solid icons
  faHome,
  faChevronRight,
  faChevronLeft,
  faXmark,
  faBars,
  faEllipsisVertical,
  faHeart,
  faBrain,
  faShield,
  faWandSparkles,
  faStar,
  faPlay,
  faForward,
  faBackward,
  faQuestion,
  faLightbulb,
  faEye,
  faHandHoldingHeart,
  faChartBar,
  faChartLine,
  faBullseye,
  faAward,
  faCheckCircle,
  faCircle,
  faClock,
  faCalendar,
  faFileText,
  faDownload,
  faShare,
  faBookOpen,
  faPrint,
  faDatabase,
  faChartPie,
  faKey,
  faCog,
  faUser,
  faUserCircle,
  faShieldAlt,
  faLock,
  faSmile,
  faFrown,
  faMeh,
  faAngry,
  faSadTear,
  faGrin,
  faKiss,
  faTree,
  faWater,
  faMountain,
  faCloud,
  faSun,
  faMoon,
  faLeaf,
  faSnowflake,
  faHandsHelping,
  faMedkit,
  faPrescriptionBottle,
  faStethoscope,
  faUserMd,
  faComments,
  faArrowRight,
  faArrowLeft,
  faArrowUp,
  faArrowDown,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faExclamationTriangle,
  faInfoCircle,
  faExclamationCircle,
  faTimes,
  faCheck,
  faPalette,
  faPaintBrush,
  faSwatchbook,
  faEyeDropper,
  faShapes,
  faCrop,
  faImage,
  
  // Regular icons
  faHeartRegular,
  faStarRegular,
  faCircleRegular,
  faCheckCircleRegular,
  faUserRegular,
  faSmileRegular,
  faFrownRegular,
  faMehRegular,
);

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
export type { IconProp } from '@fortawesome/fontawesome-svg-core';
