'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { FontAwesomeIcon, IconProp } from '@/lib/fontawesome';
import { AssessmentType } from '@/types';
import { getAssessmentTitle, getAssessmentDescription } from '@/utils/helpers';
import { useRouter } from 'next/navigation';
import ApiTestModal from '@/components/ui/ApiTestModal';
import { StorageService } from '@/utils/storage';

export default function HomePage() {
  const [selectedAssessment, setSelectedAssessment] = useState<AssessmentType | null>(null);
  const [showApiTestModal, setShowApiTestModal] = useState(false);
  const router = useRouter();

  const assessmentTypes: Array<{
    type: AssessmentType;
    icon: IconProp;
    color: string;
    gradient: string;
  }> = [
    {
      type: 'anxiety',
      icon: 'heart' as IconProp,
      color: 'text-blue-600',
      gradient: 'from-blue-500 to-indigo-600'
    },
    {
      type: 'ocd',
      icon: 'brain' as IconProp,
      color: 'text-purple-600',
      gradient: 'from-purple-500 to-pink-600'
    },
    {
      type: 'anger',
      icon: 'shield-alt' as IconProp,
      color: 'text-red-600',
      gradient: 'from-red-500 to-orange-600'
    },
    {
      type: 'general',
      icon: 'wand-sparkles' as IconProp,
      color: 'text-green-600',
      gradient: 'from-green-500 to-emerald-600'
    }
  ];

  const startJourney = () => {
    if (selectedAssessment) {
      router.push(`/assessment/${selectedAssessment}`);
    }
  };

  const handleApiKeyValidated = (apiKey: string) => {
    StorageService.saveGeminiApiKey(apiKey);
    setShowApiTestModal(false);
    // Optionally show success message or redirect
  };

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-primary-300/20 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute -bottom-40 -left-40 w-96 h-96 bg-nature-300/20 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-purple-300/10 rounded-full blur-3xl animate-float"></div>
      </div>

      <div className="relative z-10 container mx-auto px-4 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h1 className="text-5xl md:text-6xl font-bold text-gradient mb-6">
            Your Psychological Journey
          </h1>
          <p className="text-xl md:text-2xl text-calm-600 max-w-3xl mx-auto leading-relaxed">
            Embark on an immersive self-discovery experience. Understand your patterns, 
            explore your mind, and receive personalized insights powered by AI.
          </p>
          
          {/* API Test Button */}
          <div className="mt-8">
            <button
              onClick={() => setShowApiTestModal(true)}
              className="inline-flex items-center space-x-2 bg-blue-600 hover:bg-blue-700 text-white font-medium px-6 py-3 rounded-lg transition-colors shadow-lg hover:shadow-xl"
            >
              <FontAwesomeIcon icon={'stethoscope' as IconProp} className="w-4 h-4" />
              <span>Test Gemini API</span>
            </button>
            <p className="text-sm text-calm-500 mt-2">
              Validate your API key before starting an assessment
            </p>
          </div>
        </motion.div>

        {/* Features */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="grid md:grid-cols-3 gap-8 mb-16"
        >
          <div className="card p-6 text-center">
            <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <FontAwesomeIcon icon={'brain' as IconProp} className="w-6 h-6 text-primary-600" />
            </div>
            <h3 className="text-lg font-semibold text-calm-800 mb-2">
              AI-Powered Insights
            </h3>
            <p className="text-calm-600">
              Receive personalized reports generated by advanced AI, tailored to your unique responses.
            </p>
          </div>

          <div className="card p-6 text-center">
            <div className="w-12 h-12 bg-nature-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <FontAwesomeIcon icon={'shield-alt' as IconProp} className="w-6 h-6 text-nature-600" />
            </div>
            <h3 className="text-lg font-semibold text-calm-800 mb-2">
              Safe & Private
            </h3>
            <p className="text-calm-600">
              Your responses are processed securely. You control your data and can exit anytime.
            </p>
          </div>

          <div className="card p-6 text-center">
            <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mx-auto mb-4">
              <FontAwesomeIcon icon={'wand-sparkles' as IconProp} className="w-6 h-6 text-purple-600" />
            </div>
            <h3 className="text-lg font-semibold text-calm-800 mb-2">
              Immersive Experience
            </h3>
            <p className="text-calm-600">
              Journey through beautiful environments as you explore different aspects of your mind.
            </p>
          </div>
        </motion.div>

        {/* Assessment Selection */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
          className="max-w-4xl mx-auto"
        >
          <h2 className="text-3xl font-bold text-center text-calm-800 mb-8">
            Choose Your Journey
          </h2>
          
          <div className="grid md:grid-cols-2 gap-6 mb-12">
            {assessmentTypes.map((assessment, index) => (
              <motion.div
                key={assessment.type}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.5 + index * 0.1 }}
                className={`card card-hover p-6 transition-all duration-300 cursor-pointer ${
                  selectedAssessment === assessment.type
                    ? 'ring-2 ring-primary-400 bg-primary-50/50'
                    : 'hover:bg-white/70'
                }`}
                onClick={() => setSelectedAssessment(assessment.type)}
              >
                <div className="flex items-start space-x-4">
                  <div className={`p-3 rounded-lg bg-gradient-to-r ${assessment.gradient} text-white`}>
                    <FontAwesomeIcon icon={assessment.icon} className="w-8 h-8" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-semibold text-calm-800 mb-2">
                      {getAssessmentTitle(assessment.type)}
                    </h3>
                    <p className="text-calm-600 mb-4">
                      {getAssessmentDescription(assessment.type)}
                    </p>
                    <div className="flex items-center text-sm text-calm-500">
                      <span>8-10 minutes</span>
                      <span className="mx-2">•</span>
                      <span>Skip anytime</span>
                    </div>
                  </div>
                  <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center ${
                    selectedAssessment === assessment.type
                      ? 'border-primary-400 bg-primary-400'
                      : 'border-calm-300'
                  }`}>
                    {selectedAssessment === assessment.type && (
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        className="w-3 h-3 bg-white rounded-full"
                      />
                    )}
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Start Button */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: selectedAssessment ? 1 : 0.5 }}
            transition={{ duration: 0.3 }}
            className="text-center"
          >
            <button
              onClick={startJourney}
              disabled={!selectedAssessment}
              className={`btn-primary text-lg px-8 py-4 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none ${
                selectedAssessment ? 'animate-glow' : ''
              }`}
            >
              <FontAwesomeIcon icon={'play' as IconProp} className="w-5 h-5 mr-2" />
              Begin Your Journey
              <FontAwesomeIcon icon={'chevron-right' as IconProp} className="w-5 h-5 ml-2" />
            </button>
          </motion.div>

          {/* Disclaimer */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.8 }}
            className="mt-12 p-6 bg-amber-50 border border-amber-200 rounded-lg"
          >
            <p className="text-sm text-amber-800 text-center">
              <strong>Important:</strong> This assessment is for self-reflection and educational purposes only. 
              It is not a substitute for professional medical advice, diagnosis, or treatment. 
              If you are experiencing severe mental health symptoms, please consult with a qualified healthcare provider.
            </p>
          </motion.div>
        </motion.div>
      </div>

      {/* API Test Modal */}
      <ApiTestModal
        isOpen={showApiTestModal}
        onClose={() => setShowApiTestModal(false)}
        onApiKeyValidated={handleApiKeyValidated}
      />
    </div>
  );
}
